[pytest]
filterwarnings =
    ignore:'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16; use inspect.iscoroutinefunction\(\) instead:DeprecationWarning:fastapi.routing
    ignore:'asyncio.iscoroutinefunction' is deprecated and slated for removal in Python 3.16; use inspect.iscoroutinefunction\(\) instead:DeprecationWarning:starlette._utils
    ignore:Core Pydantic V1 functionality isn't compatible with Python 3.14 or greater\.:UserWarning:openai._compat
